# Install virtualbox, vagrant
# vagrant plugin install vagrant-vbguest
# vagrant up
# vagrant ssh
# cd /var/www/SmartShopper/Backend && nodemon -L app.js
# localhost:3000

$setup = <<SCRIPT
apt-get update
apt-get install -y curl git
curl -sL https://deb.nodesource.com/setup_6.x | bash -
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
echo "deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-3.2.list

apt-get update
apt-get install -y nodejs
apt-get install -y mongodb-org
sudo npm install -g nodemon

mkdir -p /data/db
chown -R mongodb /data/db
SCRIPT

$start = <<SCRIPT
mongod --fork --logpath /var/log/mongodb.log
SCRIPT

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network :forwarded_port, guest: 3000, host: 3000

  config.vm.provision :shell, :inline => $setup
  config.vm.synced_folder ".", "/var/www/SmartShopper/Backend"
  config.vm.provision :shell, run:"always", :inline => $start

  config.vm.provider :virtualbox do |vb|
    vb.name = "SmartShopper"
  end
end
